name: Upgrade Version
description: "Upgrade the NPM package version of the project"

inputs:
  github-user:
    description: "User"
    required: true
  working-directory:
    description: "Working Directory"
    required: false
    default: "."
outputs:
  current-version:
    description: "Current Version"
    value: ${{ steps.package-version.outputs.result }}



runs:
  using: "composite"
  steps:
    - name: Branch
      shell: bash
      run: git checkout "$GITHUB_HEAD_REF"

    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci

    - name: Set github user
      id: github
      shell: bash
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "${{ inputs.github-user }}"

    - name: Update Version
      shell: bash
      run: npm run release

    - name: Push version
      shell: bash
      run: git push

    - name: Get Version
      uses: actions/github-script@v6
      id: package-version
      with:
        result-encoding: string
        script: return require('./package.json').version
